version: '3.7'

services:
  db:
    container_name: terminals_mysql
    image: mysql:8.0
    restart: always
    volumes:
     - mysql_data:/var/lib/mysql
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: charity

volumes:
  mysql_data: